<?php
return [
  // Backward compatibility (default set, can map to reguler)
  'required_documents' => [
    'ktp','kk','surat_pengantar','sk_pangkat_terakhir','sk_jabatan_terakhir','skp_dua_tahun_terakhir','karpeg','drh','pernyataan_disiplin'
  ],
  // New structured documents per jenis kenaikan pangkat
  'jenis' => [
    'reguler' => [
      'SK CPNS' => 'SKCP_NIPBARU.pdf',
      'SK PNS' => 'SKPN_NIPBARU.pdf',
      'SK Kenaikan Pangkat terakhir' => 'SKKP_NIPBARU.pdf',
      'SK Jabatan pelaksana' => 'SKJP_NIPBARU.pdf',
      'Surat Tanda Lulus Ujian Dinas' => 'STLUD_NIPBARU.pdf',
      'Ijazah dan Transkrip Nilai terakhir' => 'IJZAKHIR_NIPBARU.pdf',
      'Surat Peningkatan Pendidikan atau Pencantuman gelar dari BKN' => 'SRTG_NIPBARU.pdf',
      'SK Mutasi' => 'SKMUT_NIPBARU.pdf',
    ],
    'pilihan' => [
      'SK CPNS' => 'SKCP_NIPBARU.pdf',
      'SK PNS' => 'SKPN_NIPBARU.pdf',
      'SK Kenaikan Pangkat terakhir' => 'SKKP_NIPBARU.pdf',
      'Surat Pengangkatan dalam Jabatan Struktural terakhir' => 'SKLANTIK_NIPBARU.pdf',
      'Surat Pengangkatan dalam Jabatan Struktural sebelumnya' => 'SKLANTIK1_NIPBARU.pdf',
      'Surat Pengangkatan dalam Jabatan Fungsional terakhir' => 'SKJABFUNG_NIPBARU.pdf',
      'Surat Pengangkatan dalam Jabatan Fungsional sebelumnya' => 'SKJABFUNG1_NIPBARU.pdf',
      'Surat Pernyataan Pelantikan dalam Jabatan Struktural terakhir' => 'SPP_NIPBARU.pdf',
      'Surat Pernyataan Pelantikan dalam Jabatan Struktural sebelumnya' => 'SPP1_NIPBARU.pdf',
      'Berita Acara Sumpah/Janji/Pelantikan Jabatan Fungsional' => 'BASUMP_NIPBARU.pdf',
      'Penetapan Angka Kredit (PAK) Konversi Tahun 2024' => 'PAK2024_NIPBARU.pdf',
      'Penetapan Angka Kredit (PAK) Integrasi (3 lembar)' => 'PAK1_NIPBARU.pdf',
      'Penetapan Angka Kredit (PAK) Konvensional Tahun 2022/Terakhir dimiliki' => 'PAK2022_NIPBARU.pdf',
      'Lembar Akumulasi Angka Kredit' => 'AKK_NIPBARU.pdf',
      'Lembar Predikat Kinerja Pegawai ke Angka Kredit Tahun 2024' => 'AKK1_NIPBARU.pdf',
      'PAK Konversi, PAK Integrasi dan PAK Konvensional, Lembar konversi predikat kinerja, Lembar akumulasi angka kredit' => 'PAKGAB_NIPBARU.pdf',
      'Surat Pernyataan SKP dari JPT Pratama' => 'SUPERSKP_NIPBARU.pdf',
      'Dokumen Evaluasi Kinerja Tahunan Pegawai Tahun 2023 dan Tahun 2024' => 'DOKKIN_NIPBARU.pdf',
      'Sertifikat Diklat/Uji Kompetensi Penjenjangan' => 'SERDIKLAT_NIPBARU.pdf',
      'Sertifikat Pendidik' => 'SERDIK_NIPBARU.pdf',
      'Surat Tanda Lulus Ujian Dinas' => 'STLUD_NIPBARU.pdf',
      'Surat Keputusan Pemberhentian Sementara dan Pengaktifan Kembali' => 'SKHENTIAKTV_NIPBARU.pdf',
      'Ijazah dan Transkrip Nilai terakhir' => 'IJZAKHIR_NIPBARU.pdf',
      'Surat Peningkatan Pendidikan atau Pencantuman gelar dari BKN' => 'SRTG_NIPBARU.pdf',
      'SK Mutasi' => 'SKMUT_NIPBARU.pdf',
      'SK Tubel/Ijin Belajar' => 'SKBEL_NIPBARU.pdf',
      'Surat Keputusan Inpassing PAK' => 'SKINPASS_PAK_NIPBARU.pdf',
      'Surat Keputusan Inpassing Nama Jabatan' => 'SKINPASS_NIPBARU.pdf',
    ],
    'ijazah' => [
      'SK CPNS' => 'SKCP_NIPBARU.pdf',
      'SK PNS' => 'SKPN_NIPBARU.pdf',
      'SK Kenaikan Pangkat terakhir' => 'SKKP_NIPBARU.pdf',
      'Surat Pengangkatan dalam Jabatan Fungsional terakhir' => 'SKJABFUNG_NIPBARU.pdf',
      'SK Jabatan pelaksana' => 'SKJP_NIPBARU.pdf',
      'Surat Izin Belajar' => 'SKIZNBEL_NIPBARU.pdf',
      'Surat Peningkatan Pendidikan atau Pencantuman gelar dari BKN' => 'SRTG_NIPBARU.pdf',
      'Akreditasi Program Studi' => 'AKREDSI_NIPBARU.pdf',
      'Ijazah dan Transkrip Nilai terakhir' => 'IJZAKHIR_NIPBARU.pdf',
      'Surat Tanda Lulus Ujian Penyesuaian Kenaikan Pangkat' => 'STLUDKP_NIPBARU.pdf',
      'Uraian Tugas yang Ditetapkan Pejabat Setingkat Eselon II' => 'URTUG_NIPBARU.pdf',
      'Berita Acara Sumpah/Janji/Pelantikan Jabatan Fungsional' => 'BASUMP_NIPBARU.pdf',
      'Penetapan Angka Kredit (PAK) Konversi Tahun 2024' => 'PAK2024_NIPBARU.pdf',
      'Penetapan Angka Kredit (PAK) Integrasi (3 lembar)' => 'PAK1_NIPBARU.pdf',
      'Penetapan Angka Kredit (PAK) Konvensional Tahun 2022/Terakhir dimiliki' => 'PAK2022_NIPBARU.pdf',
      'Lembar Akumulasi Angka Kredit' => 'AKK_NIPBARU.pdf',
      'Lembar Predikat Kinerja Pegawai ke Angka Kredit Tahun 2024' => 'AKK1_NIPBARU.pdf',
      'PAK Konversi, PAK Integrasi dan PAK Konvensional, Lembar konversi, predikat kinerja, Lembar akumulasi angka kredit' => 'PAKGAB_NIPBARU.pdf',
      'Surat Pernyataan SKP dari JPT Pratama' => 'SUPERSKP_NIPBARU.pdf',
      'Dokumen Evaluasi Kinerja Tahunan Pegawai Tahun 2023 dan Tahun 2024' => 'DOKKIN_NIPBARU.pdf',
      'SK Mutasi' => 'SKMUT_NIPBARU.pdf',
      'SK Tubel/Ijin Belajar' => 'SKBEL_NIPBARU.pdf',
      'Surat Keputusan Inpassing PAK' => 'SKINPASS_PAK_NIPBARU.pdf',
      'Surat Keputusan Inpassing Nama Jabatan' => 'SKINPASS_NIPBARU.pdf',
    ],
  ],
  'weights' => [ // still used by SPK logic; adapt later per jenis if needed
    'surat_pengantar' => 15,
    'sk_pangkat_terakhir' => 25,
    'sk_jabatan_terakhir' => 20,
    'skp_dua_tahun_terakhir' => 20,
    'karpeg' => 5,
    'drh' => 5,
    'pernyataan_disiplin' => 10,
  ],
  // Bobot default jika slug dokumen baru belum ada di daftar weights
  'default_weight' => 5,
  'thresholds' => [
    'approved' => 0.9,
    'consider' => 0.5,
    'min_valid_docs' => 3,
  ],
];
